### ISSUE TITLE
Redundant notifications for the same football games

### ISSUE THREAD

**Issue by indra4837** [indra4837/scraper#1]
## Description
Bot is sending multiple notifications about the same football game every 6 hours even if user has already bought the ticket or is not interested in the football match

## Tasks
- [ ] Implement options for user to interact for each new game - ['Going', 'Not Going']
- [ ] Implement a relational database (PostgreSQL?) to store user's choice and the new game information
- [ ] Stop sending repeated notifications for the same game
